api_platform:
    title: 'Animecon API'
    description: 'The centralized API for fetching information with regards AnimeCon'
    version: '0.0.1 DEV'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
