language: php

php:
    - 7.4
    - nightly

cache:
    directories:
        - .composer/cache

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - alias composer=composer\ --no-interaction && composer selfupdate
    - composer global require hirak/prestissimo

install:
    - travis_retry composer install --no-progress --no-interaction

script:
    - vendor/bin/grumphp run