name: GrumPHP

on: [push]
jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest, macos-latest, windows-latest]
                php-versions: ['7.4']
                composer-options: ['', '--prefer-lowest']
            fail-fast: false
        name: PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }} ${{ matrix.composer-options }}
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Install PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: xdebug, mbstring #optional
            -   name: Check PHP Version
                run: php -v
            -   name: Composer validate
                run: composer validate
            -   name: Composer install
                uses: php-actions/composer@v1
            -   name: Run the tests
                run: php vendor/bin/grumphp run --no-interaction
